DELETE http://localhost:3003/api/blogs/66a69c0d1a5d9cafce010b65 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2tvIiwiaWQiOiI2NmE2ODY1N2RiOWY1ZWM5ZTU2MjgzMDMiLCJpYXQiOjE3MjIxODk0MDd9.SuRMdFKCF6P1bpxhlNYVk2OxOz5Fyi4-UqLNLD_ty7k
Content-Type: application/json