
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2tvIiwiaWQiOiI2NmE1MzM0Y2IzNzEzY2E5ZDllM2EyMGYiLCJpYXQiOjE3MjIxMDM2MzF9.Ovg6ioj5NUPfpJgXsVLVBADa0It32t5bdL6dQFt-rWI

{
    "title": "Mastery of WebTokens",
    "author": "Mikko Mallikas",
    "url": "www.alfonsaberg.se",
    "likes": 12
}
