DELETE http://localhost:3003/api/blogs/66a698f5a1c3fd3b73a0e1ae HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pa2tvIiwiaWQiOiI2NmE2ODY1N2RiOWY1ZWM5ZTU2MjgzMDMiLCJpYXQiOjE3MjIxODk0MDd9.SuRMdFKCF6P1bpxhlNYVk2OxOz5Fyi4-UqLNLD_ty7k
Content-Type: application/json